name: PrivateChest
main: mohagames\PrivateChest\Main
api: 3.0.0
version: 1.1.0
depend:
  - PlotArea
commands:
  chest:
    permission: chest.cmd

permissions:
  chest.cmd:
    default: true
  chest.admin:
    default: op